#:schema https://json.schemastore.org/any.json

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp\\modules.exe"
  # Builds only the modules binary
  cmd = "go build -o ./tmp/modules.exe ./cmd/modules/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "cmd/gateway", "internal/gateway", ".git", "testing"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = ["."]
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  kill_delay = "0s"
  log = "modules-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "cyan"
  runner = "green"
  watcher = "magenta"

[log]
  main_only = false
  silent = false
  time = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true